### ISSUE TITLE
Installing IPOPT plugin

### ISSUE THREAD

**Issue by VishnuDevA7** [roboptim/roboptim-core-plugin-ipopt#33]
Hi,
How to install the IPOPT plugin  for Roboptim. I was able to install the core package without any issues. Following the same procedure throws errors such as IPOPT package not located. I am sure that I am searching at the right location!

**Comment by VishnuDevA7** [comment]
I was able to install the IPOPT plugin using this command but I do not know if this contains all the latest updates. 
sudo apt-get install coinor-libipopt-dev

**Comment by bchretien** [comment]
How did you install IPOPT? Basically, the CMake scripts rely on pkg-config to find IPOPT. You should have a file such as `/usr/lib/pkgconfig/ipopt.pc` on your system. If IPOPT is installed in a custom location (i.e. not `/usr/{local/}`), you should probably add the extra pkg-config path to `PKG_CONFIG_PATH`.

**Comment by VishnuDevA7** [comment]
I just cloned the IPOPT plugin git repository as I did with the core package. I have it installed(the repository is cloned) at \home (not /usr/local). And yes, I do find the file ipopt.pc at usr/lib/pkgconfig. So how should I add the pkg-config path and to which location/file? 

Presently I have cloned the git of Roboptim-Core repository and installed it at /home. And similarly have cloned the git of IPOPT plugin at /home.

**Comment by bchretien** [comment]
First, do you confirm that the following properly returns the IPOPT version?

    $ pkg-config ipopt --modversion

**Comment by VishnuDevA7** [comment]
Yes, I believe it returns me 3.10.1.

**Comment by bchretien** [comment]
Well, this is weird. Can you retry in a clean build directory? Just in case some cached value wreaks havoc.

Also, you can generate the CMake traces:

    $ cmake --trace .. &> traces.txt

The first relevant line contains `ADD_REQUIRED_DEPENDENCY(ipopt )`. This may help find out what's wrong. CMake just [runs pkg-config](https://github.com/Kitware/CMake/blob/a712575da1a0e6117c4682100e3b9df72b964b2a/Modules/FindPkgConfig.cmake#L70-L73), so if that works in your shell, it should also work in CMake.

**Comment by VishnuDevA7** [comment]
I cleaned it all and did the installation in a new folder all together. I get error again which says roboptim-core not found. I tried changing the location in the install prefix: 
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/your/install/prefix ..
It returns either roboptim-core not found or ipopt package not found. Currently I have roboptim-core in my home directory. Can you give me all the steps that are needed to install the plugin right from downloading it? Thanks.
