### ISSUE TITLE
Setting the parameters of IPOPT

### ISSUE THREAD

**Issue by etrigger** [roboptim/roboptim-core-plugin-ipopt#37]
Hi,
Thanks for the effort on the ipopt plugin.

I try to set some parameters on the ipopt, however, it seems that my setting has been ignored  as I didn't see the "debug-ipopt.log" in tmp folder.

solver.parameters()["ipopt.output_file"].value = "/tmp/debug-ipopt.log";
solver.parameters ()["ipopt.linear_solver"].value = "HSL_MA97";(I obtained the ACADEMIC LICENCE)

BTW, I am using roboptim-core3.2 and roboptim-core-plugin-ipopt3.2 all cloned from github today.
Ubuntu 14.04, gcc 4.8.4, Ipopt-3.12.6 compiled from source. (I have used Ipopt's get* script to download corresponding linear solver)

**Comment by bchretien** [comment]
Can you try with:

```cpp
solver.parameters()["ipopt.output_file"].value = std::string("/tmp/debug-ipopt.log");
solver.parameters ()["ipopt.linear_solver"].value = std::string("HSL_MA97");
```

**Comment by etrigger** [comment]
Hi,
Thanks. That works for me. 
Another question is the "max_iter" seems not working when I set the value as 50:
 solver.parameters()["ipopt.max_iter"].value = 50;
or
 solver.parameters()["ipopt.max_iter"].value = std::string("50");

When I check the IPOPT output file, the value is still 3000:

List of user-set options:
max_iter = 3000                  yes

**Comment by bchretien** [comment]
The maximum number of iterations is a particular parameter shared by every plugin. You can use the `"max-iterations"` key for that.

**Comment by bchretien** [comment]
I'm assuming that this solved your problem, feel free to re-open this issue if needed.
