### ISSUE TITLE
error: log4cxx does not name type

### ISSUE THREAD

**Issue by karthikeyasharma** [roboptim/roboptim-core-plugin-ipopt#39]
Hi,
When I run 'cmake ..' I noticed the following:

 -- WARNING: expecting failure for the following Schittkowski tests:
            13;16;20;25;44;55;56
-- WARNING: expecting failure for the following Schittkowski tests:
            13;16;20;25;44;55;56

Running make fetched me the following error:

In file included from /home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/src/ipopt-sparse.cc:34:0:
/home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/src/tnlp.hh:140:12: error: ‘log4cxx’ does not name a type
     static log4cxx::LoggerPtr logger;
            ^
In file included from /home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/src/tnlp.hh:231:0,
                 from /home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/src/ipopt-sparse.cc:34:
/home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/src/tnlp.hxx:45:5: error: ‘log4cxx’ does not name a type
     log4cxx::LoggerPtr Tnlp<T>::logger
     ^
src/CMakeFiles/roboptim-core-plugin-ipopt-sparse.dir/build.make:65: recipe for target 'src/CMakeFiles/roboptim-core-plugin-ipopt-sparse.dir/ipopt-sparse.cc.o' failed
make[2]: *** [src/CMakeFiles/roboptim-core-plugin-ipopt-sparse.dir/ipopt-sparse.cc.o] Error 1
make[2]: Leaving directory '/home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/build'
CMakeFiles/Makefile2:508: recipe for target 'src/CMakeFiles/roboptim-core-plugin-ipopt-sparse.dir/all' failed
make[1]: *** [src/CMakeFiles/roboptim-core-plugin-ipopt-sparse.dir/all] Error 2
make[1]: Leaving directory '/home/karthikeya/Documents/roboptim/roboptim-core-plugin-ipopt/build'
Makefile:163: recipe for target 'all' failed
make: *** [all] Error 2

Can someone please try to help on what's going on? My roboptim-core ran successfully. I have Ipopt 3.12.9 installed (linked with MUMPS). liblog4cxx is also installed. Any help is greatly appreciated.

**Comment by francois-keith** [comment]
Hi,

It appears that the current version of roboptim-core (1748d1a45) removed the dependency in liblog4cxx, but this removal has not been applied for the package roboptim-core-plugin-ipopt.

If you're building from sources, I would recommand to checkout the commit b968ddc8cd on roboptim-core (this is the last commit before liblog4cxx removal) in order to complete the compilation. Otherwise you'll have to wait until the merge request #38 passes.

PS: the warnings during the cmake are normal.

**Comment by bchretien** [comment]
@karthikeyasharma hi, sorry for the delay I'm not very active on GH for the time being. I'm finally merging the PR related to `log4cxx` (a work I started but did not finish back then...). That should solve your issue. Also, in case of problems with the `master` branches, you can always fallback to released versions (for both `core` and the solver plugins).

**Comment by bchretien** [comment]
I'm closing this as it should be solved now. If you still have a problem, feel free to re-open it. Thanks!
